version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: pokemon
      MONGODB_PASSWORD: root123
    volumes:
      - ./mongo:/data/db